apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-source-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jbla/src/flowbox-repos/k8s-data-stack-poc/postgres-source/.data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-source-pvc
  namespace: pg-source
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pg-source-pv
