apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-source-config
  namespace: pg-source
  labels:
    app: pg-source
data:
  POSTGRES_DB: maindb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-source
  namespace: pg-source
spec:
  serviceName: pg-source
  selector:
    matchLabels:
      app: pg-source
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-source
    spec:
      containers:
        - name: pg-source
          image: postgres:14.1
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          envFrom:
          - configMapRef:
              name: pg-source-config
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pg-source-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-source
  namespace: pg-source
  labels:
    app: pg-source
spec:
  selector:
    app: pg-source
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432